#este es un persistant volume
apiVersion: v1
kind: PersistentVolume
metadata:
#este es el name que llaman los pods a traves de los claims
 name: mysql-pv
#ac치 va la configuracion del volumen
spec:
 capacity:
  storage: 261
 volumeMode: Filesystem
 #kubectl get sc es el storageclass, lo podemos averiguar con comando kubectl get sc
 #lo coment칩 en la seccion de volumenes de aws
 #storageClassName: standard
  storageClassName: ""
 #accesos requeridos para los nodos 
 accessModes:
 #para usar un nodo
 # - ReadWriteOnce
 #para usar varios nodos en aws
   - ReadWriteMany
 #driver del pod
 #lo coment칩 en la seccion de volumenes de aws, porque agreg칩 csi en vez de hostPath
 #hostPath:
 # path: /var/lib/mysql
 # type: DirectoryOrCreate
 csi:
  driver:efs.csi.aws
  #ver pantallazo para volumeHandle
  volumeHandle:fs-05777hdhhde

  

 