apiVersion:v1
kind:Service
metadata:
name:mysql8
  spec:
  ports:
  port:3306 
  protocol:TCP
  targetPort:3306
  selector:
  app:mysql8 //para poder seleccionar un conjunto de pods q contengan esta etiqueta
  type:ClusterIP //tipo interno